apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-project
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: db