apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-project
data:
  WORDPRESS_DB_HOST: "mysql-svc"
  WORDPRESS_TABLE_PREFIX: "wp_"
  WORDPRESS_DEBUG: "false"